stages:
  data_cleaning:
    cmd: python src/data_cleaning.py
    deps:
    - data/raw/swiggy.csv
    - src/data_cleaning.py
    outs:
    - data/cleaned/swiggy_cleaned.csv

  data_preparation:
    cmd: python src/data_preparation.py
    params:
      - Data_Preparation.test_size
      - Data_Preparation.random_state
    deps:
      - data/cleaned/swiggy_cleaned.csv
      - src/data_preparation.py
    outs:
      - data/interim/train.csv
      - data/interim/test.csv

  date_preprocess_and_model_training:
    cmd: python src/data_preprocessing_and_model_building.py
    params:
      - Data_preprocess_and_model_training.n_estimators
      - Data_preprocess_and_model_training.learning_rate
      - Data_preprocess_and_model_training.max_depth
    deps:
      - data/interim/train.csv
      - src/data_preprocessing_and_model_building.py
    outs:
      - models/model.joblib

  evaluation:
    cmd: python src/evaluate.py
    deps:
      - src/evaluate.py
      - data/interim/train.csv
      - data/interim/test.csv
      - models/model.joblib
    outs:
      - run_information.json

  register:
    cmd: python src/register_model.py
    deps:
      - src/register_model.py
      - run_information.json